package edu.asu.diging.vspace.core.references;

public enum ReferenceType {
    BLOG_POST, BOOK, BOOK_SECTION, CONFERENCE_PAPER, JOURNAL_ARTICLE, PATENT, PODCAST, PRESENTATION, PROJECT_DELIVERABLE, PROJECT_MILESTONE, 
    SOFTWARE_DOCUMENTATION, THESIS, TECHNICAL_NOTE, WEB_PAGE,
    WORKING_PAPER, OTHER
}
