package edu.asu.diging.vspace.core.references;

public enum ReferenceType {
    BLOGPOST, BOOK, BOOK_ITEM, CONFERENCE_PAPER, ARTICLE, PATENT, PODCAST, PRESENTATION, PROJECT_DELIVERABLE,
    PROJECT_MILESTONE, COMPUTER_PROGRAM, THESIS, TECHNICAL_NOTE, WEB_PAGE, WORKING_PAPER, OTHER
}
