package edu.asu.diging.vspace.core.references;

public enum ReferenceType {
    REFERENCE_TYPE_BLOG_POST, REFERENCE_TYPE_BOOK, REFERENCE_TYPE_BOOK_SECTION, REFERENCE_TYPE_CONFERENCE_PAPER, REFERENCE_TYPE_JOURNAL_ARTICLE, REFERENCE_TYPE_PATENT, REFERENCE_TYPE_PODCAST, REFERENCE_TYPE_PRESENTATION, REFERENCE_TYPE_PROJECT_DELIVERABLE, REFERENCE_TYPE_PROJECT_MILESTONE, 
    REFERENCE_TYPE_SOFTWARE_DOCUMENTATION, REFERENCE_TYPE_THESIS, REFERENCE_TYPE_TECHNICAL_NOTE, REFERENCE_TYPE_WEB_PAGE,
    REFERENCE_TYPE_WORKING_PAPER, REFERENCE_TYPE_OTHER
}
