package edu.asu.diging.vspace.references;

public enum ReferenceType {
    BLOG_POST, BOOK, BOOK_SECTION, CONFERENCE_PAPER, JOURNAL_ARTICLE, PATENT, PODCAST, PRESENTATION, PROJECT_DEVLIVERABLE, PROJECT_MILESTONE, 
    SOFTWARE_DOCUMENTATION, THESIS, TECHNICAL_NOTE, WEB_PAGE,
    WOKRING_PAPER, OTHER
}
